### ISSUE TITLE
這是什麼😂😂

### ISSUE THREAD

**Issue by AndyChiangSH** [wei-coding/COVID-19-Taiwan-daily-data#1]
會自動更新嗎?

**Comment by wei-coding** [comment]
Andy Chiang：
會每日更新喔，不過是手動的XD
目前CDC的每日校正回歸都是用圖卡的方式給民眾觀看，這裡會手動整理最新的校正回歸資料，才能確保在機器學習或其他分析領域的資料正確性。

**Comment by AndyChiangSH** [comment]
原來是工人智慧啊XD
資料是去哪裡抓的，疾管署嗎?
